#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
#springboot整合mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.wisefly.springboot_mybatis_demo.entity